<a href="https://colab.research.google.com/github/saravkulkarni/Innovation-Lab/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
NumPy, short for Numerical Python, is a python library that is used in scientific computing. It allows you to work with arrays and matrices. Read the comments in the examples below to follow along with the code.

In [3]:
import numpy as np
# This creates a 1D array.
arr = np.array([6.81, 3.14, 8.27, 5.43 , 5.62])
# This prints the array
print(arr)
# To access an array element, you use index numbers. Indexing starts at 0
# The next line prints the third element
print(arr[2])
# Prints mean
print(np.mean(arr))
# Prints median
print(np.median(arr))
# Prints the standard deviation
print(np.std(arr))
# Prints the 87th percentile
print(np.percentile(arr, 87))

# You can also iterate though your array
# The following is an example of how you might want to use that
for x in arr:
  if x > 5.5:
    print(x)

# You can also sort your array numerically or alphabetically (if array of strings)
# For example:
print(np.sort(arr))

[6.81 3.14 8.27 5.43 5.62]
8.27
5.854
5.62
1.6941853499543664
7.5108
6.81
8.27
5.62
[3.14 5.43 5.62 6.81 8.27]


In [7]:
# You can also use NumPy for random numbers
import numpy as np
from numpy import random
# The following lines of code generate a random integer from 0 to 70
x = random.randint(70)
print(x)
# rand() generates a random float from 0 to 1
y = random.rand()
print(y)

# You can also change the code slightly to generate a random array
z = random.randint(70, size = 7)
print(z)


27
0.3471681505291053
[ 5 34 19 38  2 29 52]


## Exercise



*   Generate a random array
*   Print the median
*   From the array, remove all the values that are above the median create a new array with what you have left
* Sort the new array in ascending order



In [12]:
# You can also have 2D and 3D arrays (or indeed more if you wish)

import numpy as np
arr = np.array([[9.2,3.4,2.1], [7.8,3.9,4.8]])
print(arr)
# You can see how many dimensions there are in the array
print(arr.ndim)
# It helps to imagine 2D arrays as having columns and rows
# Indexing with 2D arrays gets a bit more tricky
# The following prints the third element on the second row
print(arr[1,2])

[[9.2 3.4 2.1]
 [7.8 3.9 4.8]]
2
4.8


In [13]:
# It is also possible to generate a random 2D array

import numpy as np
# 2D array with seven rows and four columns
x = random.randint(70, size=(7,4))
print(x)

[[29 18 42 12]
 [40 55 29 43]
 [46 21 43 15]
 [22  5 57 61]
 [23 51 58 52]
 [22 37 49 28]
 [ 8 56 69 43]]
